services:
  duo-client:
    build: ./client
    container_name: duo-client
    restart: always
    expose:
      - "3000"
    env_file:
      - ./client/.env.local
    networks:
      - shared

  duo-server:
    build: ./server
    container_name: duo-server
    restart: always
    expose:
      - "8000"
    env_file:
      - ./server/.env.production
    networks:
      - shared

networks:
  shared:
    external: true